apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: powerwall
        - name: GF_SECURITY_ADMIN_USER
          value: powerwall
        - name: POWERWALL_LOCATION
        image: docker.io/grafana/grafana:7.5.10
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-claim0
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-claim1
        - mountPath: /var/lib/grafana/dashboards
          name: grafana-claim2
      restartPolicy: Always
      volumes:
      - name: grafana-claim0
        persistentVolumeClaim:
          claimName: grafana-claim0
      - name: grafana-claim1
        persistentVolumeClaim:
          claimName: grafana-claim1
      - name: grafana-claim2
        persistentVolumeClaim:
          claimName: grafana-claim2
status: {}
