apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: telegraf
    spec:
      containers:
      - args:
        - bash
        - -xe
        - /tmp/entrypoint.sh
        env:
        - name: POWERWALL_LOCATION
        - name: POWERWALL_PASS
        image: docker.io/telegraf:1.19
        name: telegraf
        resources: {}
        volumeMounts:
        - mountPath: /tmp/entrypoint.sh
          name: telegraf-claim0
        - mountPath: /etc/telegraf
          name: telegraf-claim1
        - mountPath: /tmp/cookie
          name: telegraf-claim2
      restartPolicy: Always
      volumes:
      - name: telegraf-claim0
        persistentVolumeClaim:
          claimName: telegraf-claim0
      - name: telegraf-claim1
        persistentVolumeClaim:
          claimName: telegraf-claim1
      - name: telegraf-claim2
        persistentVolumeClaim:
          claimName: telegraf-claim2
status: {}
